name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Get tag
        id: step_get_tag_id
        uses: dawidd6/action-get-tag@v1
      
      - name: Generate changelog
        uses: scottbrenner/generate-changelog-action@master
        id: step_changelog_id
        env:
          REPO: ${{ github.repository }}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release version ${{ steps.step_get_tag_id.outputs.tag }}
          body: |
            ${{ steps.step_changelog_id.outputs.changelog }}
          draft: false
          prerelease: false
